### PR TITLE
updated & ehancement in website codebase

### PR DESCRIPTION
**Pull request by Khushalsarode**
check the outputs for ref:
Screenshot 2023-10-21 041824
Screenshot 2023-10-21 041849

more work to be done:
add organization logo's
add dark and light theme
make grid of 4 cards in row

### CODE REVIEW

**Comment by Khushalsarode** [comment]
@iriteshmishra 
can you check and merge this pr #74

**Comment by Khushalsarode** [comment]
@iriteshmishra shall I close the request?

**Comment by iriteshmishra** [comment]
Bro there is a merge conflict. I will not get option of merge until this conflict is resolved @Khushalsarode

**Comment by Khushalsarode** [comment]
> Bro there is a merge conflict. I will not get option of merge until this conflict is resolved @Khushalsarode

Got it!, i will try to add changes one by one instead of multiple at once

**Comment by iriteshmishra** [comment]
Bro, try to do it without bootstrap or tailwind because this repo is for beginners purpose and most of them might not be familiar with frameworks. Use grid or flexbox. @Khushalsarode

**Comment by iriteshmishra** [comment]
I have also added json file so that might also give you conflicts.

**Pull request closed without merging**
