### PR TITLE
added owasp and free-software-foundation

### PR DESCRIPTION
**Pull request by goobric**
added OWASP and the Free Software Foundation to the list

### CODE REVIEW

**Comment by iriteshmishra** [comment]
Hello @goobric , Thank you for contributing, There is a conflict, please resolve this.

**Comment by goobric** [comment]
hi @iriteshmishra how do I resolve this conflict?
how was 'write-access' enabled?

**Comment by iriteshmishra** [comment]
Hello @goobric , 
kindly remove the "<< == >>" arrows and remove opensource is written at line no. 293. 
Add div in the middle also. Close the div at 297 and add one div at 298
Screenshot 2023-10-22 184848

**Comment by goobric** [comment]
hi @iriteshmishra ,
do I need to fork, and clone the original repo again, and then remove the arrows?
or do I start all over again, by deleting the forked repo from my github account, and removing the cloned repo from my local computer?
Do do I change the contents of the file on your main repo?
Sorry for so many questions!

**Comment by goobric** [comment]
hi @iriteshmishra I have updated the index file, within my forked repo, see attached image. Do I now create a new PR with this file?
231023_oso_update

**Comment by iriteshmishra** [comment]
yes, you can. @goobric 
You can ask as many questions as you want, I don't mind.

**Pull request closed without merging**
