### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by karansingh1820**
Added one more open source organization name.

### CODE REVIEW

**Comment by iriteshmishra** [comment]
Bro @karansingh1820 , It's already present in the website (below outreachy). You can add a new one 👍.

**Comment by karansingh1820** [comment]
Ok. Give me some time, I will add another new one.

**Comment by karansingh1820** [comment]
plz check it i added new one one with name(The PostgreSQL Global Development Group).

**Comment by iriteshmishra** [comment]
> plz check it i added new one one with name(The PostgreSQL Global Development Group).

Yes I will merge it in few minutes, See to it that you have remove previous one (eclipse foundation).

**Comment by karansingh1820** [comment]
Ok

**Pull request merged**
