### PR TITLE
improved the home page info div

### PR DESCRIPTION
**Pull request by Khushalsarode**
added logo for website tab
modified the homepage info tab and adjustment
add style for adjustment

### CODE REVIEW

**Comment by Khushalsarode** [comment]
@iriteshmishra will this do?

**Comment by iriteshmishra** [comment]
There is a problem in search feature Its not working. Kindly look into this.
Screenshot 2023-10-28 131021

**Comment by Khushalsarode** [comment]
@iriteshmishra sure!

**Comment by iriteshmishra** [comment]
Issue #73

**Comment by Khushalsarode** [comment]
@iriteshmishra does script.js working properly, it is showing all data into webpage?

**Comment by iriteshmishra** [comment]
can you create a screen recording after your added feat how the website is looking. @Khushalsarode

**Comment by iriteshmishra** [comment]
Because when I am running the website it is looking something like this 
image

**Comment by Khushalsarode** [comment]
@iriteshmishra 
Screenshot 2023-11-14 141449

**Pull request merged**
